[project]
name = "whispercli"
version = "0.1.0"
description = "Chat with AIs via your terminal while fully respecting your privacy"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "typer>=0.19.2",
    "rich>=13.9.4",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
]